version: "3.2"
services:
  validator_1:
    container_name: validator_1
    image: decentration/pop-art:v0.9.14
    ports:
      - "30333:30333"
      - "9933:9933"
      - "9944:9944"
    command: "/usr/local/bin/polkadot --chain ./specs/rococo-pop-art.json --port 30333 --ws-port 9944 --rpc-port 9933 --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' --validator --name Decentration01"
    volumes:
      - "pop_art_validator_1:/data"
  validator_2:
    container_name: validator_2
    image: decentration/pop-art:v0.9.14
    ports:
      - "30334:30334"
      - "9934:9934"
      - "9945:9945"
    command: "/usr/local/bin/polkadot --chain ./specs/rococo-pop-art.json --port 30334 --ws-port 9945 --rpc-port 9934 --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' --validator --name Decentration02"
    volumes:
      - "pop_art_validator_2:/data"
  validator_3:
    container_name: validator_3
    image: decentration/pop-art:v0.9.14
    ports:
      - "30335:30335"
      - "9935:9935"
      - "9946:9946"
    command: "/usr/local/bin/polkadot --chain ./specs/rococo-pop-art.json --port 30335 --ws-port 9946 --rpc-port 9935 --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' --validator --name Decentration03"
    volumes:
      - "pop_art_validator_3:/data"
volumes:
  pop_art_validator_1:
  pop_art_validator_2:
  pop_art_validator_3:
  